# These are supported funding model platforms

github: [luksireiku] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: luksireiku # Replace with a single Patreon username
ko_fi: endernull # Replace with a single Ko-fi username
custom: ['https://paypal.me/luksireiku'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
