version: '3'
services:
  bot:
    build: .
    restart: unless-stopped
    container_name: polaris
    volumes:
      - ./logs:/usr/src/app/logs
      - ./.tdlib_files:/usr/src/app/.tdlib_files
      - ./docs/firebase.json:/usr/src/app/firebase.json
