version: '3'
services:
  bot:
    build: .
    restart: unless-stopped
    container_name: polaris
    volumes:
      - ./logs:/usr/src/app/logs
      - ./docs/firebase.json:/usr/src/app/firebase.json
      - ./docs/data:/usr/src/app/data
