export { AboutPlugin } from './about';
export { AnimalsPlugin } from './animals';
export { ConfigPlugin } from './config';
export { EchoPlugin } from './echo';
export { HelpPlugin } from './help';
export { LeagueOfLegendsPlugin } from './league-of-legends';
export { RemindersPlugin } from './reminders';
export { TagsPlugin } from './tags';
export { VoicePlugin } from './voice';
