name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]
    branches:
      - main
    types: 
      - completed

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: polaris

jobs:
  deploy:
    # Ensure push job passes before updating image.
    needs: push

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            docker stop ${{ env.IMAGE_NAME }}
            docker rm ${{ env.IMAGE_NAME }}
            docker run -v $PWD/logs:/usr/src/app/logs -v $PWD/docs/data:/usr/src/app/data -v $PWD/docs/firebase.json:/usr/src/app/firebase.json -p 1984:1984/tcp -ti -d --restart unless-stopped --name ${{ env.IMAGE_NAME }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
